### ISSUE TITLE
MultiDimensional Array 

### ISSUE THREAD

**Issue by katesaikishore** [voku/Arrayy#37]
array:3 [▼
  0 => Nmap\Port {#329 ▼
    -number: 22
    -protocol: "tcp"
    -state: "open"
    -service: Nmap\Service {#332 ▼
      -name: "ssh"
      -product: "OpenSSH"
      -version: "7.9p1 Raspbian 10"
    }
  }
  1 => Nmap\Port {#324 ▼
    -number: 80
    -protocol: "tcp"
    -state: "open"
    -service: Nmap\Service {#334 ▼
      -name: "http"
      -product: "Apache httpd"
      -version: "2.4.38"
    }
  }
  2 => Nmap\Port {#330 ▼
    -number: 5900
    -protocol: "tcp"
    -state: "open"
    -service: Nmap\Service {#336 ▼
      -name: "vnc"
      -product: "RealVNC Enterprise"
      -version: "5.3 or later"
    }
  }
]

I have this multidimensional array.

$arrayy = new A([$ports]); 

$arrayy->get('Nmap\Port'); // ['lastname' => 'Moelleken']
$echo = $arrayy->get('Nmap\Port.-service');
dd($echo);

When I use this code I am getting null

**Comment by voku** [comment]
Nmap\Port are instances of objects and NO arrays here. Can you show me a working example, so that I can test it, thanks.

**Comment by katesaikishore** [comment]
So converting into the array can be the solution from objects? Can you please tell to this above one working on this now!

**Comment by voku** [comment]
in version >= 7.5.0 you can use it like this: https://github.com/voku/Arrayy/commit/98e961ef66df5590fc649cb8f6d80ce6941f08b0#diff-d9413305e28638e6802d6128d290691cR5883

**Comment by katesaikishore** [comment]
Yeah Got this thank you!
