### ISSUE TITLE
Deprecation with PHP8.!

### ISSUE THREAD

**Issue by frenchcomp** [voku/Arrayy#50]
#### What is this feature about (expected vs actual behaviour)?
They are some deprecation with PHP 8.1 on implementations of PHP's standard interfaces (ArrayAccess, iterator, etc). They can be disabled by adding "#[\ReturnTypeWillChange]" before methods involved. 

#### How can I reproduce it?
Run tests with PHP 8.1

#### Does it take minutes, hours or days to fix?
The PR #49 is available.

**Comment by voku** [comment]
Thanks, merged in version 7.8.14
